version: 2.1

jobs:
  build:
    working_directory: ~/learning-vue

    docker:
      - image: circleci/node:10-browsers

    steps:
      - checkout

      - restore_cache:
          key: learning-vue-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: npm install

      - save_cache:
          key: learning-vue-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'

      - run:
          name: build
          command: npm run build
