version: 2.1

jobs:
  build-learning-vue:
    working_directory: ~/learning-vue
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: learning-vue-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: learning-vue-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: build
          command: npm run build

  test-learning-vue:
    working_directory: ~/learning-vue
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: learning-vue-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: learning-vue-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: unit test
          command: npm run test:unit
      - run:
          name: codecov
          command: npm run codecov

workflows:
  version: 2
  learning-vue-workflow:
    jobs:
      - build-learning-vue
      - test-learning-vue:
          requires:
            - build-learning-vue
